/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.toweroftrial;

/**
 *
 * @author User
 */
public class Battleframe extends javax.swing.JFrame {

private Player player;
    private Monster monster;
    private int floorNumber;

    // For launching from Tower
    public Battleframe(Player player, Monster monster, int floorNumber) {
        this.player = player;
        this.monster = monster;
        this.floorNumber = floorNumber;
        initComponents();
        updateStatsDisplay();
        jTextArea1.setText("A wild " + monster.name + " appears!");
    }

    // For demo/test
    public Battleframe() {
        this(new Player("Demo", "Warrior"), new Monster("Goblin", 75, 25, 12, 15, false), 1);
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("floor");

        jLabel2.setText("name");

        jLabel3.setText("HP");

        jLabel4.setText("MP");

        jLabel5.setText("Level");

        jLabel6.setText("Exp");

        jLabel7.setText("Monster");

        jLabel8.setText("HP");

        jLabel9.setText("MP");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Attack");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Skills");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Flee");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGap(79, 79, 79))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(31, 31, 31)
                .addComponent(jButton2)
                .addGap(33, 33, 33)
                .addComponent(jButton3)
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        private void updateStatsDisplay() {
        jLabel1.setText("Floor " + floorNumber);
        jLabel2.setText(player.name + " (" + player.playerClass + ")");
        jLabel3.setText("HP: " + player.hp + "/" + player.maxHp);
        jLabel4.setText("MP: " + player.mp + "/" + player.maxMp);
        jLabel5.setText("Level: " + player.level);
        jLabel6.setText("EXP: " + player.exp + "/" + player.expToNext);
        jLabel7.setText(monster.name);
        jLabel8.setText("HP: " + monster.hp + "/" + monster.maxHp);
        jLabel9.setText("MP: " + monster.mp + "/" + monster.maxMp);
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextArea1.setText("You fled the battle!");
        disableBattleButtons();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (player.hp <= 0 || monster.hp <= 0) return;
        int dmg = 25 + player.level * 3;
        dmg = monster.applyPassive(dmg);
        monster.hp -= dmg;
        if (monster.hp < 0) monster.hp = 0;
        jTextArea1.setText(player.name + " attacks " + monster.name + " and deals " + dmg + " damage!\n");
        updateStatsDisplay();

        if (monster.hp <= 0) {
            jTextArea1.append("You have slain the " + monster.name + "!\nYou gained " + monster.expReward + " Exp!");
            player.gainExp(monster.expReward);
            disableBattleButtons();
            updateStatsDisplay();
            return;
        }
        monsterTurn();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         if (player.hp <= 0 || monster.hp <= 0) return;
        Skill skill = player.skills.get(0);
        if (player.mp < skill.manaCost) {
            jTextArea1.setText("Not enough MP to use " + skill.name + "!");
            return;
        }
        int dmg = 40 + player.level * 4;
        dmg = monster.applyPassive(dmg);
        monster.hp -= dmg;
        player.mp -= skill.manaCost;
        if (monster.hp < 0) monster.hp = 0;
        jTextArea1.setText(player.name + " uses " + skill.name + " and deals " + dmg + " damage!\n");
        updateStatsDisplay();

        if (monster.hp <= 0) {
            player.gainExp(monster.expReward);
            jTextArea1.append("You have slain the " + monster.name + "!\nYou gained " + monster.expReward + " Exp!");
            disableBattleButtons();
            updateStatsDisplay();
            return;
        }
        monsterTurn();
    }//GEN-LAST:event_jButton2ActionPerformed
      private void monsterTurn() {
        Skill mSkill = monster.chooseSkill();
        if (mSkill == null) {
            int mobAtk = monster.attack;
            player.hp -= mobAtk;
            if (player.hp < 0) player.hp = 0;
            jTextArea1.append("\n" + monster.name + " attacks " + player.name + " for " + mobAtk + " damage!");
        } else {
            monster.mp -= mSkill.manaCost;
            if (monster.isBoss) {
                if (mSkill.name.contains("Roar")) {
                    jTextArea1.append("\nBoss uses Roar! Your attack is reduced for 2 turns! (Demo only)");
                } else if (mSkill.name.contains("Mega Slam")) {
                    int dmg2 = monster.attack + 20;
                    player.hp -= dmg2;
                    if (player.hp < 0) player.hp = 0;
                    jTextArea1.append("\nBoss uses Mega Slam! It deals " + dmg2 + " damage!");
                }
            } else {
                int dmg2 = monster.attack + 5;
                player.hp -= dmg2;
                if (player.hp < 0) player.hp = 0;
                jTextArea1.append("\n" + monster.name + " uses " + mSkill.name + " and deals " + dmg2 + " damage!");
            }
        }
        updateStatsDisplay();

        if (player.hp <= 0) {
            jTextArea1.append("\nYou have been defeated!");
            disableBattleButtons();
        }
    }

    private void disableBattleButtons() {
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Battleframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Battleframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Battleframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Battleframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Battleframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
